print("Yusuf & Sons")
p = float(input("Enter Initial Principal"))
r = float(input("Enter Interest Rate"))
t = float(input("Enter Time"))
n = float(input("Enter Number of Times"))
si = p * (1 + (r * t))
ci = p * (1 + (r / n)) ** (n * t)
print("Simple Interest:"), print(si)
print("Compound Interest:"), print(ci)
print("Thanks for your patronage")
